<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-08T13:16:48 IST" name="Default suite" finished-at="2023-11-08T13:17:36 IST" duration-ms="47470">
    <groups>
    </groups>
    <test started-at="2023-11-08T13:16:48 IST" name="Default test" finished-at="2023-11-08T13:17:36 IST" duration-ms="47470">
      <class name="com.quantela.codenet.qa.qpf_wallet_mob_ui_test.TransferFundTest">
        <test-method is-config="true" signature="suiteSetup()[pri:0, instance:com.quantela.codenet.qa.qpf_wallet_mob_ui_test.TransferFundTest@23e84203]" started-at="2023-11-08T13:16:48 IST" name="suiteSetup" finished-at="2023-11-08T13:16:48 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteSetup -->
        <test-method is-config="true" signature="AndroidDriverConfig()[pri:0, instance:com.quantela.codenet.qa.qpf_wallet_mob_ui_test.TransferFundTest@23e84203]" started-at="2023-11-08T13:16:48 IST" name="AndroidDriverConfig" finished-at="2023-11-08T13:17:08 IST" duration-ms="19765" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AndroidDriverConfig -->
        <test-method is-config="true" signature="citizenUserSignin()[pri:0, instance:com.quantela.codenet.qa.qpf_wallet_mob_ui_test.TransferFundTest@23e84203]" started-at="2023-11-08T13:17:08 IST" name="citizenUserSignin" finished-at="2023-11-08T13:17:28 IST" duration-ms="19676" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- citizenUserSignin -->
        <test-method signature="validateFundTypeText()[pri:0, instance:com.quantela.codenet.qa.qpf_wallet_mob_ui_test.TransferFundTest@23e84203]" started-at="2023-11-08T13:17:28 IST" name="validateFundTypeText" finished-at="2023-11-08T13:17:35 IST" duration-ms="7218" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Fund type] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Fund type] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.quantela.codenet.qa.qpf_wallet_mob_ui_test.TransferFundTest.validateFundTypeText(TransferFundTest.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateFundTypeText -->
        <test-method is-config="true" signature="driverQuit()[pri:0, instance:com.quantela.codenet.qa.qpf_wallet_mob_ui_test.TransferFundTest@23e84203]" started-at="2023-11-08T13:17:35 IST" name="driverQuit" finished-at="2023-11-08T13:17:36 IST" duration-ms="770" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
      </class> <!-- com.quantela.codenet.qa.qpf_wallet_mob_ui_test.TransferFundTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
